on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v3

      - name: Configure git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "${GITHUB_ACTOR}"

      - name: Install nix
        uses: cachix/install-nix-action@v20

      - name: Update flake inputs
        run: nix flake update --commit-lock-file

      - name: Push updates
        run: git push
